### ISSUE TITLE
Error unmarshalling deployment transation after successfully deployed chaincode

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#686] opened 2016-02-16 20:12 UTC
code level:
commit e338d6a25865db96c4e6374168473965a2b39054
Merge: 67e2a10 15dcc91
Author: Binh Q Nguyen binhn@us.ibm.com
Date:   Mon Feb 15 12:10:54 2016 -0500

security and privacy: enabled

After successfully deployed chaincode, there is an error unmarshalling deployment transaction message, see the error message at the end of the log below:

15:53:47.205 [rest] Deploy -> INFO 032 REST deploying chaincode...
15:53:47.216 [rest] Deploy -> INFO 033 Local user 'lukas' is already logged in. Retrieving login token.
15:53:47.244 [container] writeGopathSrc -> INFO 034 rootDirectory = /opt/gopath/src
15:53:53.515 [CRYPTO] InitClient -> INFO 035 Initializing client [lukas]...
15:53:53.516 [CRYPTO.client.lukas] init -> INFO 036 Init keystore...
15:53:53.517 [CRYPTO.client.lukas] init -> INFO 037 Init keystore...done.
15:53:53.517 [CRYPTO.client.lukas] initCryptoEngine -> INFO 038 Initializing node crypto engine...
15:53:53.541 [CRYPTO.client.lukas] initCryptoEngine -> INFO 039 Initializing node crypto engine...done!
15:53:53.541 [CRYPTO.client.lukas] init -> INFO 03a Initialization...done.
15:53:53.542 [CRYPTO.client.lukas] init -> INFO 03b Init keystore...
15:53:53.546 [CRYPTO.client.lukas] init -> INFO 03c Init keystore...done.
15:53:53.546 [CRYPTO.client.lukas] init -> INFO 03d Initialization...done.
15:53:53.547 [CRYPTO] InitClient -> INFO 03e Initializing client [lukas]...done!
15:53:53.548 [CRYPTO.client.lukas] selectNextTCert -> ERRO 03f No TCert in cache found.
15:53:54.542 [CRYPTO] closeClientInternal -> INFO 040 Closing client [lukas]...
15:53:54.542 [CRYPTO.client.lukas] close -> INFO 041 Closing keystore...
15:53:54.542 [CRYPTO.client.lukas] close -> INFO 042 Closing keystore...done!
15:53:54.543 [CRYPTO] closeClientInternal -> INFO 043 Closing client [lukas]...done! [<clean>].
15:53:54.543 [rest] Deploy -> INFO 044 Successfuly deployed chainCode: bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c.
15:53:55.627 [container] newDockerClient -> INFO 045 Creating VM with endpoint: unix:///var/run/docker.sock
15:54:03.169 [container] newDockerClient -> INFO 046 Creating VM with endpoint: unix:///var/run/docker.sock
15:54:03.358 [ledger] sendProducerBlockEvent -> ERRO 047 Error unmarshalling deployment transaction for block event: proto: can't skip unknown wire type 7 for protos.ChaincodeDeploymentSpec

**Comment by binhn** [comment] 2016-02-16 20:41
@srderson I think the problem is due to the fact the the payload is encrypted and we try to unmarshal without first decrypting it, which is quite challenging at this point as the security context may not be available

@muralisrini

**Comment by srderson** [comment] 2016-02-16 21:00
See https://github.com/openblockchain/obc-peer/pull/636/commits

Originally, I was setting the entire payload to nil. Based on suggestions, I changed this to unmarshall the payload and set the code to nil as that is the heavy part.

I can modify so that if security is enabled, the entire payload will be set to nil.

**Comment by binhn** [comment] 2016-02-16 21:54
Do we currently have a use for the payload?  If not, we should nil the entire payload whether security is on or not.  There are other fields that are encrypted, so the consumers, due to security, need to handle it.

**Comment by ibmmark** [comment] 2016-06-16 18:08
@dongmingh @bmos299 I think this might be resolved...

**Comment by dongmingh** [comment] 2016-06-17 13:21
Observed this, see timestamp 20:45:11.904 below, on commit 2bd2b4f005f90d664895c6db369d2010a4e663bd of 6/16/16 after deploy the chaincode example02

20:45:09.049 [consensus/obcpbft] processMessage -> INFO 039 Batch replica 0 received new consensus request: X8qd627JK30/SC3d2sYExOecQaZ0sI1GWLR4zjeg0wYnB2GQ/iFkKVzo75y+to3FE0EZpgy7dZIxCuqrCWiIZA==
20:45:09.063 [consensus/obcpbft] sendBatch -> INFO 03a Creating batch with 1 requests
20:45:09.075 [rest] processChaincodeDeploy -> INFO 03b Successfully deployed chainCode: 97e1a9887ad9695f8ce5b0a8d0e6f250bb75ba19db49f2f610b4c450deba0233ee41d9d00a6c1142bfb021946ab36e506e454053ad5231414d43c9fba0a601c7
20:45:09.076 [rest] ProcessChaincode -> INFO 03c REST successfully deploy chaincode: {"jsonrpc":"2.0","result":{"status":"OK","message":"97e1a9887ad9695f8ce5b0a8d0e6f250bb75ba19db49f2f610b4c450deba0233ee41d9d00a6c1142bfb021946ab36e506e454053ad5231414d43c9fba0a601c7"},"id":1}
20:45:09.085 [consensus/obcpbft/events] loop -> WARN 03d Attempting to stop an unfired idle timer
20:45:09.266 [consensus/obcpbft] executeOne -> INFO 03e Replica 0 executing/committing request for view=0/seqNo=1 and digest VgVK1yIL2VEfWrOMfqX96HtO5K+shMAh2UmkBBS4pG6DxE7wH4OGNbIUA7aucTralNwM9JZTjqzirPJ/bOiPdQ==
20:45:09.334 [consensus/obcpbft/events] loop -> WARN 03f Attempting to stop an unfired idle timer
20:45:11.904 [ledger] sendProducerBlockEvent -> ERRO 040 Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group
20:45:11.919 [consensus/obcpbft] execDoneSync -> INFO 041 Replica 0 finished execution 1, trying next

**Comment by muralisrini** [comment] 2016-06-17 13:33
@dongmingh this error trying to send an event for a secure transaction does not indicate a problem with the deploy itself

`20:45:11.904 [ledger] sendProducerBlockEvent -> ERRO 040 Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group
`

This is a known red-herring for issues (a search for "Error unmarshalling deployment" will get you other issues where this is referenced).

**Comment by christo4ferris** [comment] 2016-07-27 15:21
@dongmingh @muralisrini - @ibmmark suggested that this might be resolved. Is it? If so, please close this.

**Comment by dongmingh** [comment] 2016-07-27 16:50
with commit level:
commit 18ffe74cc9fcd2cc77933f763427467057bc2830
Author: Thomas Leplus thomasleplus@users.noreply.github.com
Date:   Fri Jul 22 13:10:41 2016 -0700

still see this error message
16:46:36.472 [ledger] sendProducerBlockEvent -> ERRO 004 Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group

**Comment by christo4ferris** [comment] 2016-08-19 17:47
closing then

**Closed as completed by christo4ferris** 2016-08-19 17:47 UTC
Labels: bug, sev2
