### ISSUE TITLE
Unable to build docker images using the updated docker file

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#934] opened 2016-04-01 19:24 UTC
Unable to build docker image using the updated docker file.

Issue observed with commit#ca2afe3.
commit ca2afe314379eb2b016d29ba1233f7b7b0aa1de4
Merge: 523fc10 fe0501f
Author: Sheehan Anderson sranderson@gmail.com

Observed openblockchain/baseimage:latest image is not found in Docker Hub.

![docker pull image](https://cloud.githubusercontent.com/assets/17034502/14217686/8d0184f4-f81d-11e5-8656-a04e4f6148ad.png)

**Comment by ghaskins** [comment] 2016-04-01 22:56
Lack of :latest tag was an intentional design decision (see https://github.com/openblockchain/obc-dev-env/blob/master/setup.sh#L83).  I believe the problem is that users need to update to the latest obc-dev-env and vagrant destroy/up to use the latest peer.

**Comment by binhn** [comment] 2016-04-18 15:37
@rameshthoomu can we close this issue?

**Comment by rameshthoomu** [comment] 2016-04-25 21:52
I don't see any issue in inside vagrant environment as we are building latest tag on vagrant up. To create :latest baseimage outside of vagrant I am executing 

```
cd /hyperledger/fabric/scripts/provision
./docker.sh 0.0.9 (tag) to build latest image.
```

observed below error message while building an image using docker files which are available in (membersrvc and consensus/docker-compose-files)

```
vagrant@hyperledger-devenv:v0.0.9-1832dfe:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc$ docker build -t image .
```

``````
Step 7 : RUN CGO_CFLAGS=" " CGO_LDFLAGS="-lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy" go install && cp $GOPATH/src/github.com/hyperledger/fabric/membersrvc/membersrvc.yaml $GOPATH/bin
 ---> Running in 3e04c0cf49d5
can't load package: package github.com/hyperledger/fabric/membersrvc: no buildable Go source files in /opt/gopath/src/github.com/hyperledger/fabric/membersrvc```
``````

**Comment by rameshthoomu** [comment] 2016-05-20 01:40
@ghaskins : any inputs on the above error message?

**Comment by ghaskins** [comment] 2016-05-20 01:53
IIRC this was because the Dockerfile was moved from its previous home in the root of the project to a subdirectory, but has COPY verbs that assumed its previous location.

Unless I am misinterpreting, we can close this out and I think the issue has been resolved.

**Closed as completed** 2016-06-16 22:31 UTC
Labels: bug, sev2
