### ISSUE TITLE
Chaincode deployment is unstable

### ISSUE THREAD

**Issue by genggjh** [hyperledger-archives/fabric#884] opened 2016-03-28 14:58 UTC
The chaincode docker image and container can not be created in my 4-vp nodes test env.

And I can find some errors like following in vp container logs:

2016-03-28T14:47:34.105117441Z 14:47:34.104 [peer] handleChat -> ERRO 01b Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error:eӌ�1��}ion canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp2"  172.17.0.5:30303 VALIDATOR ���\�y�e<����b�}@k

**Comment by tuand27613** [comment] 2016-03-28 15:21
I suspect these messages are "normal" debug logging.  What do you see in the VP logs near where the deploy chaincode transaction is executed and committed ?
If you are running pbft consensus classic/batch, search for string "commit count".

When i was having trouble with my deploy transactions a few months back, it was due to vagrant running out of resources. Which you can configure in the Vagrantfile.

**Comment by genggjh** [comment] 2016-03-29 03:25
I believe this is dock pull related issue, since the network is very slow to connect to docker.io recently from China. But anyway I think we should improve the error handler in obc.

**Comment by genggjh** [comment] 2016-03-29 09:24
I am running pbft classic, and following logs for more
2016-03-29T09:19:03.324243294Z 09:19:03.323 [consensus/obcpbft] newPbftCore -> INFO 019 PBFT log size (L) = 20
2016-03-29T09:19:09.874285159Z 09:19:09.873 [peer] handleChat -> ERRO 01a Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp2"  172.17.0.6:30303 VALIDATOR ��!�)�l04y
                                                                                                                                        Bcpvu���$����d��+��}

2016-03-29T09:21:16.410954124Z 09:21:16.409 [consensus/obcpbft] executeOne -> INFO 01b Replica 3 executing/committing request for view=0/seqNo=1 and digest nvHV2SChHTLW5DQFZbPPPBXpssGavS/zsmNA4CePAsFZ/DNANmHab7PYyvsnvWTrAREHvuNqrKp6cBmWQiIiDA==
2016-03-29T09:21:16.693404412Z 09:21:16.672 [container] newDockerClient -> INFO 01c Creating VM with endpoint: http://172.17.0.1:4243

@tuand27613 : do u mean that's a debug message and we need not care about that?

**Comment by clydedacruz** [comment] 2016-03-29 10:48
@genggjh I usually got this error when i tried to connect 2 VPs which had the same peer.address. but recently i see this error even when the peer.address values are different .

**Comment by tuand27613** [comment] 2016-03-29 12:34
i would ignore the `duplicate handler` messages for now.  

setting logging-level to debug will also help to see what's going on during the newDockerClient call.

**Comment by christo4ferris** [comment] 2016-07-25 13:09
@genggjh I am closing this as it is rather stale. Please reopen with updated observations and how to reproduce, etc if you disagree.

**Closed as completed by christo4ferris** 2016-07-25 13:09 UTC
