### ISSUE TITLE
Peer FSM failed while handling message

### ISSUE THREAD

**Issue by fubai** [hyperledger-archives/fabric#1468] opened 2016-05-13 08:32 UTC
I start a network using PBFT as consensus engine, consist of 4 peers and a ca server:

`docker run --rm -it -p 50051:50051 membersrvc membersrvc`

`docker run --rm -it -p 5000:5000 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_NETWORKID=dev0 -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.2:50051 -e CORE_SECURITY_ENROLLID=user_type4_98960925d9 -e CORE_SECURITY_ENROLLSECRET=183c3ccf30 hyperledger-peer peer node start`

`docker run --rm -it -p 5001:5000 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp1 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_NETWORKID=dev1 -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.2:50051 -e CORE_SECURITY_ENROLLID=user_type4_9ec418355e -e CORE_SECURITY_ENROLLSECRET=f3390342fb -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.3:30303 hyperledger-peer peer node start`

`docker run --rm -it -p 5002:5000 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp2 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_NETWORKID=dev2 -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.2:50051 -e CORE_SECURITY_ENROLLID=user_type4_579a123d65 -e CORE_SECURITY_ENROLLSECRET=8a410ac866 -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.3:30303 hyperledger-peer peer node start`

`docker run --rm -it -p 5003:5000 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp3 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_NETWORKID=dev3 -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.2:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.2:50051 -e CORE_SECURITY_ENROLLID=user_type4_805b8c45d8 -e CORE_SECURITY_ENROLLSECRET=521adac32f -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.3:30303 hyperledger-peer peer node start`

And I get an error message `Peer FSM failed while handling message` in vp1 and vp3, here are the logs:
### the vp0:

07:06:58.414 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
07:06:58.417 [peer] func1 -> INFO 002 Auto detected peer address: 172.17.0.3:30303
07:06:58.417 [peer] func1 -> INFO 003 Auto detected peer address: 172.17.0.3:30303
07:06:58.418 [peer] func1 -> INFO 004 Auto detected peer address: 172.17.0.3:30303
07:06:58.421 [eventhub_producer] start -> INFO 005 event processor started
07:06:58.421 [main] serve -> INFO 006 Security enabled status: true
07:06:58.423 [main] serve -> INFO 007 Privacy enabled status: true
07:06:58.424 [crypto] func1 -> INFO 008 Registering validator [user_type4_98960925d9] with name [user_type4_98960925d9]...
07:06:58.474 [crypto] func1 -> INFO 009 Registering validator [user_type4_98960925d9] with name [user_type4_98960925d9]...done!
07:06:58.475 [crypto] func1 -> INFO 00a Initializing validator [user_type4_98960925d9]...
07:06:58.487 [crypto] func1 -> INFO 00b Initializing validator [user_type4_98960925d9]...done!
07:06:58.488 [chaincode] NewChaincodeSupport -> INFO 00c Chaincode support using peerAddress: 172.17.0.3:30303
07:06:58.526 [state] loadConfig -> INFO 00d Loading configurations...
07:06:58.527 [state] loadConfig -> INFO 00e Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[maxGroupingAtEachLevel:%!s(int=5) bucketCacheSize:%!s(int=100) numBuckets:%!s(int=1000003)], deltaHistorySize=[500]
07:06:58.527 [state] NewState -> INFO 00f Initializing state implementation [buckettree]
07:06:58.527 [buckettree] initConfig -> INFO 010 configs passed during initialization = map[string]interface {}{"maxGroupingAtEachLevel":5, "bucketCacheSize":100, "numBuckets":1000003}
07:06:58.527 [buckettree] initConfig -> INFO 011 Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[4:321 2:13 8:200001 7:40001 6:8001 9:1000003 5:1601 1:3 3:65 0:1] hashFunc:0xa71530}
07:06:58.527 [buckettree] newBucketCache -> INFO 012 Constructing bucket-cache with max bucket cache size = [100] MBs
07:06:58.528 [buckettree] loadAllBucketNodesFromDB -> INFO 013 Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
07:06:58.528 [genesis] func1 -> INFO 014 Creating genesis block.
07:06:58.528 [genesis] loadConfigs -> INFO 015 Loading configurations...
07:06:58.528 [genesis] loadConfigs -> INFO 016 Configurations loaded: genesis=map[chaincodes:<nil>], mode=[], deploySystemChaincodeEnabled=[false]
07:06:58.528 [genesis] func1 -> INFO 017 No genesis block chaincodes defined.
07:06:58.529 [genesis] 1 -> INFO 018 Adding 0 system chaincodes to the genesis block.
07:06:58.531 [consensus/controller] NewConsenter -> INFO 019 Creating consensus plugin pbft
07:06:58.532 [consensus/obcpbft] newPbftCore -> INFO 01a PBFT type = *obcpbft.obcClassic
07:06:58.532 [consensus/obcpbft] newPbftCore -> INFO 01b PBFT Max number of validating peers (N) = 4
07:06:58.532 [consensus/obcpbft] newPbftCore -> INFO 01c PBFT Max number of failing peers (f) = 1
07:06:58.533 [consensus/obcpbft] newPbftCore -> INFO 01d PBFT byzantine flag = false
07:06:58.533 [consensus/obcpbft] newPbftCore -> INFO 01e PBFT request timeout = 2s
07:06:58.533 [consensus/obcpbft] newPbftCore -> INFO 01f PBFT view change timeout = 2s
07:06:58.533 [consensus/obcpbft] newPbftCore -> INFO 020 PBFT Checkpoint period (K) = 10
07:06:58.533 [consensus/obcpbft] newPbftCore -> INFO 021 PBFT Log multiplier = 4
07:06:58.533 [consensus/obcpbft] newPbftCore -> INFO 022 PBFT log size (L) = 40
07:06:58.534 [consensus/obcpbft] restoreLastSeqNo -> INFO 023 Replica 0 restored lastExec: 0
07:06:58.535 [consensus/obcpbft] restoreState -> INFO 024 Replica 0 restored state: view: 0, seqNo: 0, pset: 0, qset: 0, reqs: 0, chkpts: 1
07:06:58.536 [main] serve -> INFO 025 Starting peer with id=name:"vp0" , network id=dev0, address=172.17.0.3:30303, discovery.rootnode=, validator=true
07:06:58.537 [rest] StartOpenchainRESTServer -> INFO 026 Initializing the REST service on 0.0.0.0:5000, TLS is disabled.
07:07:07.533 [consensus/util] RegisterChannel -> INFO 027 Registering connection from <nil>
07:07:15.344 [consensus/util] RegisterChannel -> WARN 028 Received duplicate connection from <nil>, switching to new connection
07:07:22.884 [consensus/util] RegisterChannel -> WARN 029 Received duplicate connection from <nil>, switching to new connection
### the vp1:

07:07:06.406 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
07:07:06.408 [peer] func1 -> INFO 002 Auto detected peer address: 172.17.0.4:30303
07:07:06.410 [peer] func1 -> INFO 003 Auto detected peer address: 172.17.0.4:30303
07:07:06.411 [peer] func1 -> INFO 004 Auto detected peer address: 172.17.0.4:30303
07:07:06.414 [main] serve -> INFO 005 Security enabled status: true
07:07:06.414 [main] serve -> INFO 007 Privacy enabled status: true
07:07:06.414 [eventhub_producer] start -> INFO 006 event processor started
07:07:06.416 [crypto] func1 -> INFO 008 Registering validator [user_type4_9ec418355e] with name [user_type4_9ec418355e]...
07:07:06.465 [crypto] func1 -> INFO 009 Registering validator [user_type4_9ec418355e] with name [user_type4_9ec418355e]...done!
07:07:06.465 [crypto] func1 -> INFO 00a Initializing validator [user_type4_9ec418355e]...
07:07:06.475 [crypto] func1 -> INFO 00b Initializing validator [user_type4_9ec418355e]...done!
07:07:06.476 [chaincode] NewChaincodeSupport -> INFO 00c Chaincode support using peerAddress: 172.17.0.4:30303
07:07:06.501 [state] loadConfig -> INFO 00d Loading configurations...
07:07:06.504 [state] loadConfig -> INFO 00e Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[numBuckets:%!s(int=1000003) maxGroupingAtEachLevel:%!s(int=5) bucketCacheSize:%!s(int=100)], deltaHistorySize=[500]
07:07:06.505 [state] NewState -> INFO 00f Initializing state implementation [buckettree]
07:07:06.505 [buckettree] initConfig -> INFO 010 configs passed during initialization = map[string]interface {}{"bucketCacheSize":100, "numBuckets":1000003, "maxGroupingAtEachLevel":5}
07:07:06.506 [buckettree] initConfig -> INFO 011 Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[6:8001 1:3 8:200001 5:1601 4:321 3:65 2:13 9:1000003 0:1 7:40001] hashFunc:0xa71530}
07:07:06.506 [buckettree] newBucketCache -> INFO 012 Constructing bucket-cache with max bucket cache size = [100] MBs
07:07:06.508 [buckettree] loadAllBucketNodesFromDB -> INFO 013 Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
07:07:06.508 [genesis] func1 -> INFO 014 Creating genesis block.
07:07:06.509 [genesis] loadConfigs -> INFO 015 Loading configurations...
07:07:06.510 [genesis] loadConfigs -> INFO 016 Configurations loaded: genesis=map[chaincodes:<nil>], mode=[], deploySystemChaincodeEnabled=[false]
07:07:06.511 [genesis] func1 -> INFO 017 No genesis block chaincodes defined.
07:07:06.514 [genesis] 1 -> INFO 018 Adding 0 system chaincodes to the genesis block.
07:07:06.516 [consensus/controller] NewConsenter -> INFO 019 Creating consensus plugin pbft
07:07:06.517 [consensus/obcpbft] newPbftCore -> INFO 01a PBFT type = *obcpbft.obcClassic
07:07:06.517 [consensus/obcpbft] newPbftCore -> INFO 01b PBFT Max number of validating peers (N) = 4
07:07:06.517 [consensus/obcpbft] newPbftCore -> INFO 01c PBFT Max number of failing peers (f) = 1
07:07:06.518 [consensus/obcpbft] newPbftCore -> INFO 01d PBFT byzantine flag = false
07:07:06.518 [consensus/obcpbft] newPbftCore -> INFO 01e PBFT request timeout = 2s
07:07:06.518 [consensus/obcpbft] newPbftCore -> INFO 01f PBFT view change timeout = 2s
07:07:06.519 [consensus/obcpbft] newPbftCore -> INFO 020 PBFT Checkpoint period (K) = 10
07:07:06.519 [consensus/obcpbft] newPbftCore -> INFO 021 PBFT Log multiplier = 4
07:07:06.520 [consensus/obcpbft] newPbftCore -> INFO 022 PBFT log size (L) = 40
07:07:06.521 [consensus/obcpbft] restoreLastSeqNo -> INFO 023 Replica 1 restored lastExec: 0
07:07:06.521 [consensus/obcpbft] restoreState -> INFO 024 Replica 1 restored state: view: 0, seqNo: 0, pset: 0, qset: 0, reqs: 0, chkpts: 1
07:07:06.522 [main] serve -> INFO 025 Starting peer with id=name:"vp1" , network id=dev1, address=172.17.0.4:30303, discovery.rootnode=172.17.0.3:30303, validator=true
07:07:06.522 [rest] StartOpenchainRESTServer -> INFO 026 Initializing the REST service on 0.0.0.0:5000, TLS is disabled.
07:07:07.539 [consensus/util] RegisterChannel -> INFO 027 Registering connection from <nil>
07:07:18.744 [consensus/util] RegisterChannel -> WARN 028 Received duplicate connection from <nil>, switching to new connection
07:07:28.577 [consensus/util] RegisterChannel -> WARN 029 Received duplicate connection from <nil>, switching to new connection
07:07:29.158 [consensus/util] RegisterChannel -> WARN 02a Received duplicate connection from <nil>, switching to new connection
07:07:29.160 [peer] handleChat -> ERRO 02b Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp3"  172.17.0.6:30303 VALIDATOR ?E????R֨??,wPEeKڄS???}
### the vp2:

07:07:14.218 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
07:07:14.220 [peer] func1 -> INFO 002 Auto detected peer address: 172.17.0.5:30303
07:07:14.221 [peer] func1 -> INFO 003 Auto detected peer address: 172.17.0.5:30303
07:07:14.223 [peer] func1 -> INFO 004 Auto detected peer address: 172.17.0.5:30303
07:07:14.225 [main] serve -> INFO 005 Security enabled status: true
07:07:14.226 [main] serve -> INFO 007 Privacy enabled status: true
07:07:14.227 [crypto] func1 -> INFO 008 Registering validator [user_type4_579a123d65] with name [user_type4_579a123d65]...
07:07:14.225 [eventhub_producer] start -> INFO 006 event processor started
07:07:14.278 [crypto] func1 -> INFO 009 Registering validator [user_type4_579a123d65] with name [user_type4_579a123d65]...done!
07:07:14.279 [crypto] func1 -> INFO 00a Initializing validator [user_type4_579a123d65]...
07:07:14.295 [crypto] func1 -> INFO 00b Initializing validator [user_type4_579a123d65]...done!
07:07:14.295 [chaincode] NewChaincodeSupport -> INFO 00c Chaincode support using peerAddress: 172.17.0.5:30303
07:07:14.328 [state] loadConfig -> INFO 00d Loading configurations...
07:07:14.328 [state] loadConfig -> INFO 00e Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[bucketCacheSize:%!s(int=100) numBuckets:%!s(int=1000003) maxGroupingAtEachLevel:%!s(int=5)], deltaHistorySize=[500]
07:07:14.329 [state] NewState -> INFO 00f Initializing state implementation [buckettree]
07:07:14.329 [buckettree] initConfig -> INFO 010 configs passed during initialization = map[string]interface {}{"bucketCacheSize":100, "numBuckets":1000003, "maxGroupingAtEachLevel":5}
07:07:14.329 [buckettree] initConfig -> INFO 011 Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[5:1601 2:13 1:3 7:40001 6:8001 8:200001 4:321 0:1 3:65 9:1000003] hashFunc:0xa71530}
07:07:14.329 [buckettree] newBucketCache -> INFO 012 Constructing bucket-cache with max bucket cache size = [100] MBs
07:07:14.330 [buckettree] loadAllBucketNodesFromDB -> INFO 013 Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
07:07:14.330 [genesis] func1 -> INFO 014 Creating genesis block.
07:07:14.330 [genesis] loadConfigs -> INFO 015 Loading configurations...
07:07:14.332 [genesis] loadConfigs -> INFO 016 Configurations loaded: genesis=map[chaincodes:<nil>], mode=[], deploySystemChaincodeEnabled=[false]
07:07:14.334 [genesis] func1 -> INFO 017 No genesis block chaincodes defined.
07:07:14.336 [genesis] 1 -> INFO 018 Adding 0 system chaincodes to the genesis block.
07:07:14.338 [consensus/controller] NewConsenter -> INFO 019 Creating consensus plugin pbft
07:07:14.339 [consensus/obcpbft] newPbftCore -> INFO 01a PBFT type = *obcpbft.obcClassic
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 01b PBFT Max number of validating peers (N) = 4
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 01c PBFT Max number of failing peers (f) = 1
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 01d PBFT byzantine flag = false
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 01e PBFT request timeout = 2s
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 01f PBFT view change timeout = 2s
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 020 PBFT Checkpoint period (K) = 10
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 021 PBFT Log multiplier = 4
07:07:14.340 [consensus/obcpbft] newPbftCore -> INFO 022 PBFT log size (L) = 40
07:07:14.340 [consensus/obcpbft] restoreLastSeqNo -> INFO 023 Replica 2 restored lastExec: 0
07:07:14.340 [consensus/obcpbft] restoreState -> INFO 024 Replica 2 restored state: view: 0, seqNo: 0, pset: 0, qset: 0, reqs: 0, chkpts: 1
07:07:14.341 [main] serve -> INFO 025 Starting peer with id=name:"vp2" , network id=dev2, address=172.17.0.5:30303, discovery.rootnode=172.17.0.3:30303, validator=true
07:07:14.345 [rest] StartOpenchainRESTServer -> INFO 026 Initializing the REST service on 0.0.0.0:5000, TLS is disabled.
07:07:15.348 [consensus/util] RegisterChannel -> INFO 027 Registering connection from <nil>
07:07:18.746 [consensus/util] RegisterChannel -> WARN 028 Received duplicate connection from <nil>, switching to new connection
07:07:26.369 [consensus/util] RegisterChannel -> WARN 029 Received duplicate connection from <nil>, switching to new connection
### the vp3:

07:07:21.788 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
07:07:21.790 [peer] func1 -> INFO 002 Auto detected peer address: 172.17.0.6:30303
07:07:21.790 [peer] func1 -> INFO 003 Auto detected peer address: 172.17.0.6:30303
07:07:21.792 [peer] func1 -> INFO 004 Auto detected peer address: 172.17.0.6:30303
07:07:21.794 [main] serve -> INFO 005 Security enabled status: true
07:07:21.795 [main] serve -> INFO 007 Privacy enabled status: true
07:07:21.795 [eventhub_producer] start -> INFO 006 event processor started
07:07:21.795 [crypto] func1 -> INFO 008 Registering validator [user_type4_805b8c45d8] with name [user_type4_805b8c45d8]...
07:07:21.842 [crypto] func1 -> INFO 009 Registering validator [user_type4_805b8c45d8] with name [user_type4_805b8c45d8]...done!
07:07:21.842 [crypto] func1 -> INFO 00a Initializing validator [user_type4_805b8c45d8]...
07:07:21.851 [crypto] func1 -> INFO 00b Initializing validator [user_type4_805b8c45d8]...done!
07:07:21.851 [chaincode] NewChaincodeSupport -> INFO 00c Chaincode support using peerAddress: 172.17.0.6:30303
07:07:21.868 [state] loadConfig -> INFO 00d Loading configurations...
07:07:21.869 [state] loadConfig -> INFO 00e Configurations loaded. stateImplName=[buckettree], stateImplConfigs=map[bucketCacheSize:%!s(int=100) numBuckets:%!s(int=1000003) maxGroupingAtEachLevel:%!s(int=5)], deltaHistorySize=[500]
07:07:21.869 [state] NewState -> INFO 00f Initializing state implementation [buckettree]
07:07:21.869 [buckettree] initConfig -> INFO 010 configs passed during initialization = map[string]interface {}{"numBuckets":1000003, "maxGroupingAtEachLevel":5, "bucketCacheSize":100}
07:07:21.870 [buckettree] initConfig -> INFO 011 Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:5 lowestLevel:9 levelToNumBucketsMap:map[7:40001 0:1 1:3 9:1000003 6:8001 4:321 3:65 2:13 8:200001 5:1601] hashFunc:0xa71530}
07:07:21.871 [buckettree] newBucketCache -> INFO 012 Constructing bucket-cache with max bucket cache size = [100] MBs
07:07:21.871 [buckettree] loadAllBucketNodesFromDB -> INFO 013 Loaded buckets data in cache. Total buckets in DB = [0]. Total cache size:=0
07:07:21.871 [genesis] func1 -> INFO 014 Creating genesis block.
07:07:21.872 [genesis] loadConfigs -> INFO 015 Loading configurations...
07:07:21.873 [genesis] loadConfigs -> INFO 016 Configurations loaded: genesis=map[chaincodes:<nil>], mode=[], deploySystemChaincodeEnabled=[false]
07:07:21.873 [genesis] func1 -> INFO 017 No genesis block chaincodes defined.
07:07:21.874 [genesis] 1 -> INFO 018 Adding 0 system chaincodes to the genesis block.
07:07:21.875 [consensus/controller] NewConsenter -> INFO 019 Creating consensus plugin pbft
07:07:21.876 [consensus/obcpbft] newPbftCore -> INFO 01a PBFT type = *obcpbft.obcClassic
07:07:21.877 [consensus/obcpbft] newPbftCore -> INFO 01b PBFT Max number of validating peers (N) = 4
07:07:21.877 [consensus/obcpbft] newPbftCore -> INFO 01c PBFT Max number of failing peers (f) = 1
07:07:21.878 [consensus/obcpbft] newPbftCore -> INFO 01d PBFT byzantine flag = false
07:07:21.878 [consensus/obcpbft] newPbftCore -> INFO 01e PBFT request timeout = 2s
07:07:21.879 [consensus/obcpbft] newPbftCore -> INFO 01f PBFT view change timeout = 2s
07:07:21.879 [consensus/obcpbft] newPbftCore -> INFO 020 PBFT Checkpoint period (K) = 10
07:07:21.879 [consensus/obcpbft] newPbftCore -> INFO 021 PBFT Log multiplier = 4
07:07:21.880 [consensus/obcpbft] newPbftCore -> INFO 022 PBFT log size (L) = 40
07:07:21.880 [consensus/obcpbft] restoreLastSeqNo -> INFO 023 Replica 3 restored lastExec: 0
07:07:21.880 [consensus/obcpbft] restoreState -> INFO 024 Replica 3 restored state: view: 0, seqNo: 0, pset: 0, qset: 0, reqs: 0, chkpts: 1
07:07:21.881 [main] serve -> INFO 025 Starting peer with id=name:"vp3" , network id=dev3, address=172.17.0.6:30303, discovery.rootnode=172.17.0.3:30303, validator=true
07:07:21.882 [rest] StartOpenchainRESTServer -> INFO 026 Initializing the REST service on 0.0.0.0:5000, TLS is disabled.
07:07:22.887 [consensus/util] RegisterChannel -> INFO 027 Registering connection from <nil>
07:07:26.371 [consensus/util] RegisterChannel -> WARN 028 Received duplicate connection from <nil>, switching to new connection
07:07:28.584 [consensus/util] RegisterChannel -> WARN 029 Received duplicate connection from <nil>, switching to new connection
07:07:29.157 [consensus/util] RegisterChannel -> WARN 02a Received duplicate connection from <nil>, switching to new connection
07:07:29.161 [peer] handleChat -> ERRO 02b Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: ?????p?????andle, F0o?\?tp?????a&}1"  172.17.0.4:30303 VALIDATOR

**Comment by clydedacruz** [comment] 2016-05-13 09:56
Im seeing the same error . When nodes 2 and 3 join the discovery root node , the warnings about the duplicate handler show up . When the 4th node joins the error appears : `Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler`

**Comment by bcbrock** [comment] 2016-05-13 12:42
This is a duplicate of #685 which has been open for 3 months. @srderson @ghaskins Can we get this marked as a bug and on a "fix list"? It may be as simple as de-escalating the severity.

**Comment by bmos299** [comment] 2016-05-13 15:38
@srderson  @ghaskins @bcbrock what should be our process for dups such as this?

**Comment by bcbrock** [comment] 2016-05-13 21:48
I think it's OK to close duplicates with a note as to why (i.e., it is a duplicate). The poster can always re-open if they disagree and explain why it is not a duplicate.

**Closed as completed** 2016-05-13 21:51 UTC
Labels: duplicate

**Comment by Abigale001** [comment] 2016-08-20 02:11
I met the same error with you. But there are so many links from this issue to that issue. Although there are about four or five issues the same, I can't still find the real solution. @bcbrock could you please tell me how you fix it?
