### ISSUE TITLE
Deploy does not return Transaction ID when vp3 (of set of 4) is lagged out

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1076] opened 2016-04-12 19:27 UTC
Description:

PBFT classic set of 4 VPs does not return a TID asynchronously if one of the set is paused, doesn't send back the response with the TID till the paused docker image is unpaused.

Steps to repro:
1.  Setup pbft of 4 (vp0-vp3)
2.  Use docker pause on vp3
3.  Send Deploy to remaining peers
4.  Note postman used to send deploy seems stuck
5.  Send another deploy
6.  Still nothing
7.  Restart vp3 using docker unpause
8.  Look at logs as deploys finally return what was meant to be an async call after many minutes of waiting.

Results:

Pausing one of the vps (simulating network drop) causes the process of sending a deploy to hang until the system is unpaused (or until the network connection is restored)

Expected Results:
1.  An async response should go back immediately.
2.  A server disconnected from the network should not cause remaining servers to wait indefinitely for its return

Logs:

More to come...

**Comment by corecode** [comment] 2016-04-13 07:38
Quite possibly this is related to #1056

**Comment by bmos299** [comment] 2016-05-16 13:40
@RicHernandez2 @2016Nishi is #1472 a duplicate of this issue?

**Comment by RicHernandez2** [comment] 2016-05-16 13:47
Indeed, it seems to be the same issue.

**Comment by corecode** [comment] 2016-06-02 10:45
Related #1056

**Comment by ibmmark** [comment] 2016-06-16 17:41
Verified, ok to close

**Closed as completed** 2016-06-16 17:48 UTC
Labels: bug, consensus
