### ISSUE TITLE
REST API /chain/blocks/<n> returns empty blocks (other than block 0)

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1091] opened 2016-04-13 18:19 UTC
This issue is observed in conjunction with another error case, see #920. When a test program makes the REST API call /chain/blocks/<n>, it gets a normal HTTP response but the data is NULL, i.e., the block has no transactions. I don't think this makes sense except for the genesis block. This issue is observed in

```
commit 92cc78029d04736928c3c07b7c3336023de2d747
Merge: c4b31f9 96210ef
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Sun Apr 10 21:17:43 2016 -0400

    Merge pull request #1044 from ghaskins/rebrand
```

and is easy to reproduce if required.

@jyellick offered the following opinion in #920:

  My suspicion is that the peer is currently performing state transfer and so his block height does not    necessarily match the number of blocks he has. This is probably fooling the error checking that exists at that layer which assumes the chain is always unbroken.

  I think we need to think about a policy for more clearly handling requests when a replica knows its state is not complete. Do we make a best effort to return a correct result? Do we reject all queries? This seems like it should be a well studied problem, maybe <at>chetmurthy could weigh in?

**Comment by bcbrock** [comment] 2016-04-16 00:26
I can confirm that I am seeing this, see #920. What is being returned is null (not sure is this is really the empty string, or something that prints as "null")

```
vagrant@hyperledger-devenv:v0.0.9-0c353b1:/opt/gopath/src/github.ibm.com/bcbrock/busywork/scripts$ curl http://172.17.0.2:5000/chain/blocks/71
null
```

**Comment by jyellick** [comment] 2016-04-16 01:14
@bcbrock I wouldn't rule out that this is state transfer related, it's possible that in this scenario, state transfer is being invoked so many times, it is producing some gaps that are for whatever reason not being filled in, I'll investigate this possibility. (Though I'll agree, this should reply with an error, rather than an empty block if it is missing)

**Comment by bcbrock** [comment] 2016-04-17 20:08
@jyellick I was a bit optimistic when I said in #920 that the runs were going to completion. I'm seeing now that as often as not they actually fail in various ways. I assume it is best to wait until this issue (1091) is fixed before posting the other issues, would you agree?

I can also add here that the evidence suggests that if peer 0 has empty blocks in its blockchain, peer 0  also appears not to have executed every transaction.

**Comment by bcbrock** [comment] 2016-05-04 13:28
This issue is still active, even after the numerous updates made yesterday. I was incorrect earlier when I said I thought it was gone; this was due to misconfiguration uncovered by #1343.

**Comment by jyellick** [comment] 2016-05-04 14:34
@bcbrock By this issue do you mean the 'empty block' problem? If so, I think @srderson may be the most qualified person to investigate. (Or, @srderson if you'd like me to try to track this down, let me know)

In my stress tests, I'm unable to even force a view change via DOS anymore, if you could upload your logs at DEBUG (or at least with consensus/obcpbft and consensus/statetransfer at debug), I would like to see how it is that one or more of your replicas are being forced into statetransfer.

**Comment by bcbrock** [comment] 2016-05-05 15:35
@jyellick @tuand27613 Yes, I mean the 'empty block' problem. This may have something for @srderson to look at, however it is clear that the peer with the corrupted blockchain is not executing every transaction. 

This 10K transaction run generates 1GB of logs even with the limitations suggested, so I think it will be best for you to try to recreate it yourselves. This is how:
1. Install https://github.ibm.com/bcbrock/busywork
2. cd busywork/scripts; make images 
3. cd busywork/counters; make issue1091

FWIW, messages like this always appear

```
/home/bcbrock/vp2_logs/stderr:[31m15:17:33.995 [consensus/statetransfer] stateThread -> ERRO 98025[0m name:"vp2"  could not retrieve blocks as recent as 2240 as the block hash advertised
/home/bcbrock/vp2_logs/stderr:[31m15:17:33.997 [consensus/statetransfer] stateThread -> ERRO 9803c[0m name:"vp2"  believed its state for block 2240 to be valid, but its hash (7e73a9c972a8566e04f84547c3f1277f94f5350d4ce54393818af529f272b067a1e28ac453bdc698c9c837a64af5e8529fe0d07bcb8a9c155e64293fc13f517e) did not match the recovered blockchain's (b9b4e2ee523d16d9cf54d2181d3947f0932ed6572588e7f756095cff5622b07dfb21d47afeff70e209f98681ab41055d1a918fd71ed35c5815162c5ebd5be7ba)
```

**Comment by jyellick** [comment] 2016-05-05 19:30
@bcbrock Agreed, it sounds like there is some other PBFT bug lurking here.  I was no longer able to reproduce the stress bugs with my local testing setup, so thanks for the instructions to configure yours.  I will do that, and post back here once I have results.

**Comment by bcbrock** [comment] 2016-05-23 16:53
I'm seeing the same or similar issue in PBFT Batch. Here the block data is not NULL; Instead the block has no transactions as you can see from visual inspection of the JSON response. (I need to improve the error reporting of my code).

```
fabricLogger:ERROR: Block 1386 JSON response does not parse
fabricLogger:ERROR: HTTP 'ncode' = '200'
fabricLogger:ERROR: Full HTTP token dump below; Aborting
fabricLogger:ERROR:     sock sock3a8b9b0
fabricLogger:ERROR:     http HTTP/1.1 200 OK
fabricLogger:ERROR:     querylength 0
fabricLogger:ERROR:     -queryblocksize 8192
fabricLogger:ERROR:     state body
fabricLogger:ERROR:     charset iso8859-1
fabricLogger:ERROR:     type application/json
fabricLogger:ERROR:     -binary false
fabricLogger:ERROR:     url http://0.0.0.0:42278/chain/blocks/1386
fabricLogger:ERROR:     -keepalive 0
fabricLogger:ERROR:     -timeout 0
fabricLogger:ERROR:     socketinfo 0.0.0.0:42278
fabricLogger:ERROR:     queryoffset 0
fabricLogger:ERROR:     binary 1
fabricLogger:ERROR:     -strict 1
fabricLogger:ERROR:     totalsize 329
fabricLogger:ERROR:     -validate 0
fabricLogger:ERROR:     -protocol 1.1
fabricLogger:ERROR:     connection close
fabricLogger:ERROR:     -queryprogress 
fabricLogger:ERROR:     -headers 
fabricLogger:ERROR:     -blocksize 8192
fabricLogger:ERROR:     coding 
fabricLogger:ERROR:     status ok
fabricLogger:ERROR:     body {"stateHash":"8fXq0WPlgjERRs/fhMpz8TIp9vCtHlBH+7y1N8V3ihcD5o3sNNpRdCO6W83tfJv0JycexOObeS5N+jSpG+IeJQ==","previousBlockHash":"j1L3tebPQYlzq4f+ef96t9+ZIn6AXxgWiT6Oe1kOddyvccjgtTcOnzUozkRoqUV9OufApkWhBr3pfs7/Xb8spw==","consensusMetadata":"COoK","nonHashData":{"localLedgerCommitTimestamp":{"seconds":1464022054,"nanos":791764525}}}

fabricLogger:ERROR:     currentsize 329
fabricLogger:ERROR:     meta Access-Control-Allow-Headers {accept, content-type} Access-Control-Allow-Origin * Content-Type application/json Date {Mon, 23 May 2016 16:47:34 GMT} Content-Length 329 Connection close
fabricLogger:ERROR:     -type application/x-www-form-urlencoded
```

**Comment by jyellick** [comment] 2016-05-23 21:06
@bcbrock Just wanted to mention this is on the radar, and we are working through it.  The above PR should make it more transparent from a query perspective when a replica is out of date.  Changes to prevent this scenario from occurring are still being actively worked.

**Comment by bcbrock** [comment] 2016-05-23 21:15
@jyellick Thanks

**Comment by corecode** [comment] 2016-05-24 14:20
What happens if the replica crashes during state transfer?  On restart, will it reply with empty blocks?  Why does it reply with empty blocks in the first place?  It seems there is some sort of transaction missing in the ledger/state transfer.

**Comment by jyellick** [comment] 2016-05-24 15:17
In general, state transfer works from the front backwards, ie, you tell it the latest block hash and height, it grabs these, and attempts to go back to its most recent block.  However, if something goes wrong during state transfer, then it might be given a new target hash, and it starts over again.  So, once state transfer 'completes', you can have a blockchain which looks like:

0, 1, 2, 3, _, _, 6, 7, 8, 9, _, _, _, 13, 14, 15

Those are not empty blocks, they are missing blocks, and, generally speaking (with the exception of blocks which contained a deploy transaction), the peer can operate just fine with missing blocks, so long as its current state and lead block are 'current'.  State transfer continues to work in the background, to fill in these gaps, and should eventually catch up.

My strong suspicion is that the ledger, when queried assumes that if the block height is 16, that all blocks below 16 are present, and so probably does not do error checking, and allocates an empty block, shoves the content of block 10 (which is missing) into it, and returns it, and voila, you get your empty block.  This is another case where we probably need the API enhanced to give more sophisticated error reporting. (Though returning an empty block is still unacceptable, and should be fixed)

The other half, and I think the way you are more likely to see this, is the scenario where the network is processing tons of transactions, and then stops.
1. Replica falls behind, starts eavesdropping for what 'current is'
2. Tells state transfer, "go to block 20", state transfer starts
3. Tells state transfer, "block 30 would be fine too"
4. Tells state transfer, "or block 40"
5. State transfer comes back and says "Alright, we got to block 20"
6. PBFT is waiting for the checkpoint for block 50, to tell state transfer to go there, but it never comes
7. The peer is left with blocks up to 20, and none beyond.

I'm planning to put together a PR so that at after step 5, PBFT will tell state transfer "go to block 40", which should help to more quickly and completely recover.  And the null requests from #1454 would equivalently, though more slowly fix this problem.

And in quick explanation to the natural question of "why does state transfer not simply automatically go to block 40?" the answer is briefly, that for a consensus protocol like PBFT, which has a 'window' of requests, we can recover to anywhere in that window, and still be fine.  So, imagine a different case.
1. Replica falls behind, starts eavesdropping for what 'current is'
2. Tells state transfer, "go to block 20", state transfer starts
3. Tells state transfer, "block 30 would be fine too"
4. State transfer finishes, and says "Alright, we got to block 20"
5. PBFT sees that it still has what it needs to make blocks 21-30 in its store, so simply executes those requests and catches up.

**Comment by jyellick** [comment] 2016-05-26 18:29
@bcbrock After some investigation, it looks to me like this is indeed a consensus problem.  Although the investigation discovered some problems in the ledger access patterns (see #1608) that does not seem to be the root of this issue.  Instead, and the reason is unclear, it seems that we _must_ be invoking `Begin/Exec/Commit` with no transactions, and empty blocks are being created.  This seems likely to be yet another race, so I'll be focussing to continue the patch series from #1586 and #1595 to eliminate the multi-threading from PBFT and hopefully summarily squash all of these bugs.

**Comment by bcbrock** [comment] 2016-05-27 20:32
@jyelick I checked yesterday to see if maybe a transaction was failing with an error, which might have created an empty block (?), but they all looked OK.

**Comment by bcbrock** [comment] 2016-05-27 21:01
@jyellick Here are errors we're getting now running **busywork** test `stress2s` (4-node Sieve)

```
/home/bcbrock/.busywork/vp3/stderr:15:55:52.860 [consensus/obcpbft] executeVerifySet -> ERRO 1930 Replica 3 executing stale request , this indicates a bug
/home/bcbrock/.busywork/vp3/stderr:15:55:53.856 [peer] handleChat -> ERRO 19d3 Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
/home/bcbrock/.busywork/vp3/stderr:15:55:55.042 [consensus/statetransfer] stateThread -> ERRO 1b1c name:"vp3"  has a state for block 6907 which is too far out of date to play forward to block 7309, max deltas are 200, invalidating
/home/bcbrock/.busywork/vp3/stderr:15:55:55.042 [consensus/statetransfer] stateThread -> ERRO 1b1f name:"vp3"  believed its state for block 7309 to be valid, but its hash (8314fb9a88d5e2afa978d46ae19f871b373eb5bdea168e52c1c89f74c320aed9977363194fcc2b39746e272cfa5d39534f9ca79a5abeba0b83275a65a64c491a) did not match the recovered blockchain's (f3a30798e9acde537083383eb837df6fa46d2538c6bd5565dde74f340bccaa868429a0f6fdbaf27dbbf1768fb6199bb67d298b4f6230b1e45c822c2d0469ea41)
/home/bcbrock/.busywork/vp3/stderr:15:55:57.190 [consensus/statetransfer] stateThread -> ERRO 1cd7 name:"vp3"  has a state for block 7349 which is too far out of date to play forward to block 7719, max deltas are 200, invalidating
/home/bcbrock/.busywork/vp3/stderr:15:55:57.190 [consensus/statetransfer] stateThread -> ERRO 1cd9 name:"vp3"  believed its state for block 7719 to be valid, but its hash (dc58abaa239b2308e04b00ee4b981b002a6df5d9d63842323ab3a80e1a8d334ceee9a5b7bb59c7771309ea5d3ec4520e7db45cf5939e4f0da01bb24c01c0cb14) did not match the recovered blockchain's (e0c6e28b2da9c4b4b2cb000723a3f50bd1f85c1a864fe1020413d6f7d212f6ebb7caf4994056bd02b303e4fe37a5b563861d0f3663d7a8725fb95ad4b3bc3e1e)
/home/bcbrock/.busywork/vp3/stderr:15:55:58.856 [peer] handleChat -> ERRO 1d7e Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
/home/bcbrock/.busywork/vp3/stderr:15:55:59.310 [consensus/obcpbft] executeVerifySet -> ERRO 1de0 Replica 3 executing stale request , this indicates a bug
/home/bcbrock/.busywork/vp3/stderr:15:55:59.310 [consensus/obcpbft] executeVerifySet -> ERRO 1de1 Replica 3 executing stale request , this indicates a bug
/home/bcbrock/.busywork/vp3/stderr:15:56:03.856 [peer] handleChat -> ERRO 1de2 Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created

```

**Comment by jyellick** [comment] 2016-05-27 21:12
@bcbrock For the next few weeks, the focus is on hardening the batch PBFT implementation, so any Sieve related bugs are likely to be left for later investigation.  I would recommend focusing your testing away from Sieve.

**Comment by jyellick** [comment] 2016-06-09 15:47
@bcbrock Just as a quick update, thanks to your new busywork integration, I'm now able to recreate this using stress2b.  The two PRs above should partially address this, and after I finish the PR series which removes the race potentials, I'll be investigating to try to find the remaining issues.

**Closed as completed** 2016-06-15 01:05 UTC
Labels: bug, ledger
