### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#714] opened 2016-02-22 19:02 UTC
obc-peer crashes with today's code:
see detail log:
[crash.txt](https://github.com/openblockchain/obc-peer/files/141209/crash.txt)

fatal error: concurrent map read and map write

goroutine 1087982 [running]:
runtime.throw(0xe7cfa0, 0x21)
        /opt/go/src/runtime/panic.go:530 +0x90 fp=0xc8210bc1f0 sp=0xc8210bc1d8
runtime.mapaccess2_faststr(0xb5d080, 0xc820186b70, 0xdb4970, 0x4, 0x10, 0x10)
        /opt/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8210bc250 sp=0xc8210bc1f0
github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging.(_moduleLeveled).IsEnabledFor(0xc8201551c0, 0x4, 0xdb4970, 0x4, 0x0)
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging/level.go:105 +0x61 fp=0xc8210bc2b0 sp=0xc8210bc250
github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging.(_Logger).IsEnabledFor(0xc820187590, 0x4, 0x7fe80a71d000)
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging/logger.go:126 +0x4d fp=0xc8210bc2e0 sp=0xc8210bc2b0
github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging.(_Logger).log(0xc820187590, 0x4, 0xedb0e0, 0x3e, 0xc8211a3790, 0x1, 0x1)
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging/logger.go:130 +0x2f fp=0xc8210bc350 sp=0xc8210bc2e0
github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging.(_Logger).Info(0xc820187590, 0xedb0e0, 0x3e, 0xc8211a3790, 0x1, 0x1)
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging/logger.go:208 +0x5c fp=0xc8210bc390 sp=0xc8210bc350
github.com/openblockchain/obc-peer/openchain/rest.(_ServerOpenchainREST).Invoke(0xc8211a26a0, 0x7fe80a6d8990, 0xc8215b6fc0, 0xc8215b6fe0)
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/rest/rest_api.go:672 +0xb22 fp=0xc8210bc548 sp=0xc8210bc390
runtime.call32(0xc820154d80, 0xf41c28, 0xc827f3f400, 0x2000000020)
        /opt/go/src/runtime/asm_amd64.s:472 +0x3e fp=0xc8210bc570 sp=0xc8210bc548
reflect.Value.call(0xbfe020, 0xf41c28, 0x13, 0xdacce8, 0x4, 0xc8210bcb28, 0x3, 0x3, 0x0, 0x0, ...)
        /opt/go/src/reflect/value.go:435 +0x120d fp=0xc8210bc8c0 sp=0xc8210bc570
reflect.Value.Call(0xbfe020, 0xf41c28, 0x13, 0xc8210bcb28, 0x3, 0x3, 0x0, 0x0, 0x0)
        /opt/go/src/reflect/value.go:303 +0xb1 fp=0xc8210bc920 sp=0xc8210bc8c0
github.com/openblockchain/obc-peer/vendor/github.com/gocraft/web.middlewareStack.func1(0x7fe80a6d8990, 0xc8215b6fc0, 0xc8215b6fe0)
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/gocraft/web/router_serve.go:135 +0xec7 fp=0xc8210bcb78 sp=0xc8210bc920
github.com/openblockchain/obc-peer/openchain/rest.(_ServerOpenchainREST).SetResponseType(0xc8211a26a0, 0x7fe80a6d8990, 0xc8215b6fc0, 0xc8215b6fe0, 0xc8211a26c0)
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/rest/rest_api.go:90 +0x122 fp=0xc8210bcba8 sp=0xc8210bcb78
runtime.call64(0xc820154d40, 0xf41c50, 0xc820d4f4d0, 0x2800000028)
        /opt/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc8210bcbf0 sp=0xc8210bcba8

**Comment by dongmingh** [comment] 2016-02-22 19:09
steps to recreate:
1. run query continuously for 5 min with SoupUI
2. stop query
3. run invoke continuously for 5 min with SoupUI
4. crash occurs

**Comment by dongmingh** [comment] 2016-02-22 20:07
golang race detector output: 
[crash-race-output.txt](https://github.com/openblockchain/obc-peer/files/141341/crash-race-output.txt)

This time, it crashes while running query only.

**Comment by muralisrini** [comment] 2016-02-22 20:27
This appears to stem from the strictness of golang 1.6 : 

_The runtime has added lightweight, best-effort detection of concurrent misuse of maps. As always, if one goroutine is writing to a map, no other goroutine should be reading or writing the map concurrently. If the runtime detects this condition, it prints a diagnosis and crashes the program. The best way to find out more about the problem is to run the program under the race detector, which will more reliably identify the race and give more detail._

This stack and other stacks like this all stem from within go-logging (for example, IsEnabledFor call). Its not clear if our usage is suspect or there's an issue in the package.

**Comment by corecode** [comment] 2016-02-23 11:15
seems we need to start fixing other code we're using, like go-logging.

**Comment by muralisrini** [comment] 2016-02-23 13:23
@corecode , that does seem a possibility. However if this related to the changes in this PR (specifically calling SetLevel in non-initialization paths) perhaps we can contain it for now.... hope to know more after investigation today

**Comment by dongmingh** [comment] 2016-02-23 15:14
I ran an overnight test with an engineer build by commenting out the logging message as Murali pointed out. The tps remains 130 for invokes after 6+ hours.  But this morning there are "database or disk is fill" message on the window with obcca-server command.  This issue is tracked in bug #718.

Today I will test the temporary fix from @adecaro

**Comment by dongmingh** [comment] 2016-02-23 17:58
I tested the temporary fix from @adecaro this morning, run query for 20 min then run invoke for 80 min and do not see crash.  The performance remains the same as tps = 235 and 130 for query and invoke respectively.

**Comment by muralisrini** [comment] 2016-02-23 18:19
Thanks, @dongmingh. 

We were not sure if the problem was in go-logging or in the way we were using it. It is only with this PR that we see this go-logging related crash. So whatever we are doing with that package prior to this PR is correct till proven otherwise. 

Commenting out initialize-log-per-client code avoids the problem. We could try to figure out the right way to maintain that semantics. I suspect that's going to be a bit of work and may not be worth the effort ? An alternative might be to initialize log once at the beginning and write logs for all clients to it (in PR #705 ), thus avoiding write-read collisions. What do you think @adecaro ?

**Comment by adecaro** [comment] 2016-02-24 10:54
@muralisrini, @dongmingh I updated the PR to have a centralized log. I took the opportunity to introduce in main.go a line to initialize the crypto layer.

Please, @dongmingh, may you test the updated PR, if the performance are still 'good'. I will merge. Thanks :)

**Comment by dongmingh** [comment] 2016-02-24 17:45
@adecaro :
The setting and results are as follow with your latest PR code.

test setting:
security enabled
privacy enabled
TLS enabled
rootcert: file: "/var/openchain/production/.obcca/tlsca.cert"
logging: peer and crypto : error

results:
batch = 200, tps (query/invoke) = 236/147
batch = 500, tps (query/invoke) = 236/135

**Comment by dongmingh** [comment] 2016-02-24 19:47
git pull from master after @muralisrini approved PR #705 and test again, the tps results remain the same

**Comment by bmos299** [comment] 2016-02-24 20:52
Closing as per Murali and Dongming.

**Closed as completed by bmos299** 2016-02-24 20:52 UTC
