### ISSUE TITLE
obc-peer PBFT Classic does not work on queue after two VPs bounce

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#925] opened 2016-04-01 14:29 UTC
Description:

PBFT does not recognize or make any effort to recognize two VPs that _were_ down but rejoined, Deploy sent during downphase is queued, but does not execute once the two VPs are back up, resending query for it indefinitely does nothing.  BUT once you send another deploy, the system starts processing the queue and finds the results of the first deploy.

Steps to repro:
1. Setup PBFT classic (note, this is still yesterday's mid-day build) vp0-vp3
2. Stop 2 peers
3. Send a new deploy
4. Capture the TID
5. Send a Query on the TID
6. Wait as long as you like, keep sending them
7. Bring 2 stopped peers back up
8. Repeat steps 5 and 6
9. Send a new deploy
10. Send the query from step 5 again

Results:

After bringing two VPs of a set of 4 down under pbft classic, the system errors to queries based on TIDs from deploys sent when there were only 2 VPs up, as expected, but when the remaining VPs come back up, the two that stayed up are not aware of their return and continue to be non-operational towards an in queue deploy, sending queries does not move the system to start processing it's queue.  The moment you send another deploy, then a flurry of activity occurs, the deploy that you sent in step 3 gets processed and you are able to query on it.

Expected Results:

The system should recognize when VPs come back to the fold and it has enough to do consensus, then immediately begin to process its queue.

[1of4 query v deploy.txt](https://github.com/openblockchain/obc-peer/files/199778/1of4.query.v.deploy.txt)
[2of4 query v deploy.txt](https://github.com/openblockchain/obc-peer/files/199776/2of4.query.v.deploy.txt)
[3of4 query v deploy.txt](https://github.com/openblockchain/obc-peer/files/199775/3of4.query.v.deploy.txt)
[4of4 query v deploy.txt](https://github.com/openblockchain/obc-peer/files/199777/4of4.query.v.deploy.txt)

**Comment by corecode** [comment] 2016-04-01 14:40
You cannot stop 2 VPs at the same time - this violates the F=1 criterion.

**Comment by RicHernandez2** [comment] 2016-04-01 18:29
That's the point of the test though, to ensure proper functioning after disaster recovery.

**Comment by corecode** [comment] 2016-04-01 18:40
This will not work, by design (so far).  I opened #351 a long time ago to discuss requirements and scenarios.

**Comment by RicHernandez2** [comment] 2016-04-06 20:30
Uploading logs again, move to hyperledger killed the links...
[1of4 query v deploy.txt](https://github.com/hyperledger/fabric/files/207298/1of4.query.v.deploy.txt)
[2of4 query v deploy.txt](https://github.com/hyperledger/fabric/files/207300/2of4.query.v.deploy.txt)
[3of4 query v deploy.txt](https://github.com/hyperledger/fabric/files/207299/3of4.query.v.deploy.txt)
[4of4 query v deploy.txt](https://github.com/hyperledger/fabric/files/207301/4of4.query.v.deploy.txt)

**Comment by kchristidis** [comment] 2016-04-21 15:53
@vukolic Given that we got f=2, aren't all bets off? How should we proceed here?

**Comment by corecode** [comment] 2016-04-21 16:01
#1000 will address this

**Comment by vukolic** [comment] 2016-04-21 18:17
I concur with @corecode - we discussed this in scope of #1000

**Comment by corecode** [comment] 2016-05-09 13:44
This should be addressed by now.  Please verify with latest master and close if resolved.

**Comment by RicHernandez2** [comment] 2016-05-09 20:28
Both Nishi and I tested this today, her with the Go SDK, me with Postman.

We both had inconsistent results.  After bringing two VPs down, issuing deploys, then bringing them up again, then sending new deploys, we did not, as before, see the VPs start to work on their queue and new deploy.  Tried to reproduce the issue and they DID process their queue and new deploy.  Nishi is currently writing a Go test to repeat the test all night and we'll report our findings in the morning.

**Comment by bmos299** [comment] 2016-05-16 13:56
@RicHernandez2 @corecode after reading #933 is this working as designed?  Another transaction needs to be sent to start the sync process?

**Comment by bmos299** [comment] 2016-06-06 14:28
@corecode any thoughts on this issue?

**Comment by corecode** [comment] 2016-06-06 17:50
A lot of code has gone in, and the original issue should be resolved.

**Comment by ibmmark** [comment] 2016-06-16 17:38
@bmos299 tested and resolved... can be closed

**Closed as completed** 2016-06-16 17:48 UTC
Labels: bug, consensus, sev2
