### ISSUE TITLE
Getting error while building peer

### ISSUE THREAD

**Issue by vips77** [hyperledger-archives/fabric#1413] opened 2016-05-09 15:05 UTC
I am getting following error while building _peer_ after setting up my development environment and GOPATH. 
$ go build
 github.com/hyperledger/fabric/vendor/github.com/tecbot/gorocksdb
../vendor/github.com/tecbot/gorocksdb/backup.go:4:11: fatal error: 'rocksdb/c.h' file not found
 #include "rocksdb/c.h"
          ^
1 error generated.

No modifications done to the cloned copy of fabric code. The file backup.go seems to have this line commented:
![screen shot 2016-05-09 at 10 56 51 am](https://cloud.githubusercontent.com/assets/19255883/15117292/db64723a-15d4-11e6-8499-c012783505e1.png)

**Comment by mastersingh24** [comment] 2016-05-09 15:58
@vips77  - you need to add the CGO options to the _go build_ command.  Assuming rocksdb is located in _/opts/rocksdb_:

CGO_CFLAGS=-I/opt/rocksdb/include
CGO_LDFLAGS=-L/opt/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy

_CGO_CFLAGS="-I/opt/rocksdb/include" CGO_LDFLAGS="-L/opt/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy" go build_

**Comment by smithbk** [comment] 2016-05-09 21:50
This error also occurs is you try to build the peer outside of vagrant, which I've tried before :-(
Did you do this from a window where you issued "vagrant ssh" or another non-vagrant window?

**Comment by vips77** [comment] 2016-05-09 23:48
Thank you @smithbk and @mastersingh24 for pointing in right direction.

@smithbk - yes, I was trying to build from non-vagrant window. So, problem got corrected when I built from same window as vagrant ssh. :-)

**Comment by lehors** [comment] 2016-05-11 14:42
@vips77 please close this issue if the problem is fixed?

**Closed as completed** 2016-05-11 15:38 UTC
