### ISSUE TITLE
Error unmarshalling message

### ISSUE THREAD

**Issue by gongsu832** [hyperledger-archives/fabric#1204] opened 2016-04-21 19:01 UTC
```
commit c99b36458cafe7ff5b0876cad80f5aef688b3568
Merge: eb15a3b 78bdb2e
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Wed Apr 20 14:59:39 2016 -0400

    Merge pull request #1181 from rameshthoomu/travisci

    Updated travis.yml file with hyperledger/fabric changes
```

4 nodes, security+privacy enabled, consensus=PBFT. Standard chaincode_example02 used for the tests.

After successfully login and deploy the chaincode, an error unmarshalling message appears on vp0, vp1, and vp3 but not vp2:

```
[31m14:47:34.312 [ledger] sendProducerBlockEvent -> ERRO 702 Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group
```

Debug level logs for all 4 peers attached.
[rest_peer_log.zip](https://github.com/hyperledger/fabric/files/230549/rest_peer_log.zip)

**Comment by adecaro** [comment] 2016-04-22 11:09
@gongsu832, that error is caused by the fact that transactions at that time are encrypted. Actually, the event manager should be reworked to deal with confidentiality.

**Comment by tuand27613** [comment] 2016-04-22 13:09
@binh @murali your perspective ?

**Comment by prjayach** [comment] 2016-04-22 14:42
I am consistently hitting this error for multiple chaincodes including the asset_management example, when running with security in net mode. Would appreciate a quick fix. Thanks!

**Comment by prjayach** [comment] 2016-04-22 14:42
To add, I am not seeing this problem when security is turned off.

**Comment by muralisrini** [comment] 2016-04-22 14:45
@adecaro : this is technically not part of the "event framework".  This error is caused when a  block has a deploy transaction. We attempt to decrypt the tran so we can remove the large payload. But you are right on the whole ... we need to consider reconsider confidentiality in general in the context of events (part of #857).

@prjayach : are you using event infrastructure ? If not this should not cause any functional problems. If this is just an annoyance, perhaps just suppressing the message for now could be an option.

**Comment by prjayach** [comment] 2016-04-22 15:11
This happens whenever I try to deploy chaincode -- the deploy fails with this error message (docker container isn't there). So, certainly more than just annoyance.

We are using the event infrastructure, but this error itself is seen independently of it.

**Comment by muralisrini** [comment] 2016-04-22 15:43
@prjayach you;d get this error even if deploy chaincode had succeeded. If we are looking for deploy transaction errors, we would need to look at peer logs.

**Comment by prjayach** [comment] 2016-04-22 15:57
Here is a snapshot of the log for asset_management for noops on one node with security -- also tested with same result on pbft, 4 nodes, with security in case that matters

[issue1204.txt](https://github.com/hyperledger/fabric/files/232153/issue1204.txt)

**Comment by tuand27613** [comment] 2016-04-22 21:23
@prjayach  I am also seeing this error message in the logs when doing #1185 but as @muralisrini mentioned, it is not affecting login/deploy/invoke/query operations.

Suggest you re-try with security+privacy+pbft in latest environment ?  I would drop noops at this point .

**Comment by adecaro** [comment] 2016-04-23 05:37
@muralisrini, I agree with you. Sorry for the imprecise answer.

@prjayach, May you tell me how do you prepare the transaction to invoker the asset_management chaincode?

**Comment by prjayach** [comment] 2016-04-23 07:19
/peer chaincode deploy -u jim -p github.com/hyperledger/fabric/examples/chaincode/go/asset_management -c '{"Function": "init03", "Args": []}'

**Comment by prjayach** [comment] 2016-04-23 07:24
@tuand27613 I am seeing this in a 4 node deployment with pbft as well.

**Comment by adecaro** [comment] 2016-04-24 05:56
Right now, a very simple workaround would be to simply skip confidential transactions. There is no way to unmarshall their contents without first decrypting them.

**Comment by tuand27613** [comment] 2016-04-25 18:56
I'm seeing a different error when deploying asset_management which I describe in #1247 

Suggest we all use #1247 to handle @prjayach 's deploy problem.

We can keep this issue or #900 to deal with the unmarshalling issue.

**Comment by tuand27613** [comment] 2016-04-29 20:25
This is best handled as part of #857 

@gongsu832  could you close this one ?

**Comment by gongsu832** [comment] 2016-04-29 20:34
@tuand27613 sure.

**Closed as completed** 2016-04-29 20:34 UTC
Labels: bug, ledger
