### ISSUE TITLE
chaincode image needs to be created after state transfer of new deploy transaction

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#1603] opened 2016-05-26 12:34 UTC
## Description

When state transfer obtains a new block that contains a deploy transaction, the chaincode subsystem needs to create a corresponding docker image.
## Describe How to Reproduce

See #1472

@muralisrini @jyellick

**Comment by jyellick** [comment] 2016-05-26 15:05
@corecode I think this is the wrong solution.

@muralisrini There's been a fair amount of discussion about not storing the chaincodes on the block, but instead storing them in the state.  Otherwise, we're going to need to transfer 100% of the blockchain before we can start participating.  Similarly, it also seems to exclude the possibility of pruning the blockchain.

**Comment by muralisrini** [comment] 2016-05-26 15:11
@jyellick couple of points
- Agree about storing chaincode on state. We have played with that idea a bit but will be done in the chaincode life-cycle work
- regardless of where it is stored, chaincode still needs to be accessed and docker image created (if not found). This could happen potentially for many reasons. This issue is for that

**Comment by jyellick** [comment] 2016-05-26 16:03
@muralisrini I guess I'm unsure why this should be tied to state transfer? It seems like if the container crashes, or the system reboots, that the containers will also be gone.  Seems like containers should be launched on demand if they don't exist? Or is this some sort of latency problem that says they need to deploy these ahead of time?

**Comment by muralisrini** [comment] 2016-05-26 16:16
@jyellick right, that's how I read this issue. As suggested in #1472 the issue really is "chaincode image need to be created if one does not exist". Basically we launch the chaincode on demand and if that fails with "image not found" create the image too.  I guess "state transfer" merely refers to the scenario that surfaced this issue in the first place ?

**Comment by jyellick** [comment] 2016-05-26 16:49
@muralisrini Ah okay, I read this as "state transfer need to inspect each block as it arrives, and deploy any chaincodes which it contains".  If that's not how it was intended, great, then is seems like we are on the same page.

To me, the bigger problem here, is that we don't know if a particular block is needed.

Imagine the scenario where the network is at block 8,000,000 and a peer is at block 7,000,000.  It does a state transfer, and now has block 8,000,000, and its state corresponds to block 8,000,000, but it is missing blocks 7,000,001 through 7,999,999.  Aside from the chaincodes which might reside in those blocks, there's no technical reason that the peer cannot start executing transactions and creating new blocks.  In fact, that was the whole argument for transferring state snapshots rather than playing transactions forward via blocks.  But, we have no way to know if those missing blocks contain a deployed chaincode, which is a problem.

**Comment by muralisrini** [comment] 2016-05-26 17:20
@jyellick : now that you mention it, I hope that's not the intent. Chaincode does not know anything about block arrivals or consensus. The separation is clean and we'd better have a VERY good reason to break the separation. 

My interpretation of this issue was based on _The peer, vp1, still does not have a docker image and container for the 2nd deployed transaction._ in #1472

> Shutdown vp1.
> Run a new deploy transaction. The remaining 4 peers successfully execute the 2nd chaincode deploy transaction.
> Run 10 invokes on the 2nd deployed transaction. All 4 remaining peers are in sync in terms of chain height and block hashes.
> Start vp1.
> Run continuous invoke transactions on the 2nd deployed transaction at a rate of 1 invoke per second.
> vp1 occasionally catches up in chain height with matching block hashes, but still lags behind. The peer, vp1, still does not have a docker image and container for the 2nd deployed transaction.

When needed (on an invoke, say) we can and should create the image from the transaction if it exists.

**Comment by jyellick** [comment] 2016-05-26 17:55
@muralisrini Sounds like my interpretation was incorrect (hence my opposition), if this is simple covering the fact that 'the recovery mechanism also need to work after state transfer', then we're on the same page.

**Closed as completed** 2016-06-08 14:19 UTC
