### ISSUE TITLE
PBFT: queue full

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#920] opened 2016-03-31 20:22 UTC
code level:
commit 6ef721d1ad93c786db37ae6ee44cd2623dfca1d8
Merge: 0b3f7b1 ba5fffe
Author: Sheehan Anderson sranderson@gmail.com
Date:   Wed Mar 30 18:28:33 2016 -0400

```
Merge pull request #914 from muralisrini/convert_lang_to_upper_/issue#912

convert chaincode lang arg toupper
```

setup:
1. 4 docker-composer with classic PBFT, security enabled
2. login lukas
3. deploy example02
4. use SoapUI to generate invokes transaction with threads=100
5. the transaction halts with the following message on vp0:

20:13:42.216 [consensus/obcpbft] Execute -> ERRO 002 name:"vp0"  error queueing request (queue full) for sequence number 78
20:13:42.223 [consensus/obcpbft] Execute -> ERRO 003 name:"vp0"  error queueing request (queue full) for sequence number 79
20:13:51.093 [consensus/statetransfer] stateThread -> ERRO 004 name:"vp0"  could not retrieve blocks as recent as 80 as the block hash advertised

**Comment by jyellick** [comment] 2016-03-31 20:39
@dongmingh Could you provide logs at DEBUG level for all replicas?

**Comment by jyellick** [comment] 2016-03-31 20:48
This message has also been seen by @bcbrock in issue #879, what I believe is occurring here, is that a PBFT replica falls behind, seeing that the rest of the network has moved on to processing requests outside of its sliding watermark window, and initiates state transfer.  Before state transfer can complete, the network attempts to queue more transactions than the queue can accommodate, this is not a bug, but rather a side effect of the network being so busy. That error message should probably be reduced to a warning message.

The real problem here, is is likely related to `ERRO 004 name:"vp0" could not retrieve blocks as recent as 80 as the block hash advertised`.  Once PBFT advertises a block hash, it should be available on the network, and this will be the issue that needs investigating.

**Comment by dongmingh** [comment] 2016-04-01 15:01
This issue seems to be intermittent.  I am unable to recreate it this morning when attempting to collect logs for @jyellick 
I did not see the issue yesterday morning when verifying the fix of #879.  Then the issue occurred last afternoon in my test.
If I see the issue again, I will capture logs and attach here.

**Comment by tuand27613** [comment] 2016-04-11 18:30
@dongmingh  any luck ?

**Comment by bcbrock** [comment] 2016-04-13 17:33
@tuand27613 @jyellick I am seeing this in this release:

```
commit 92cc78029d04736928c3c07b7c3336023de2d747
Merge: c4b31f9 96210ef
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Sun Apr 10 21:17:43 2016 -0400

    Merge pull request #1044 from ghaskins/rebrand

    DEVENV: Rebrand vagrant environment to hyper ledger
```

With 4 peers running "classic" PBFT:

```
11:19:57.556 [consensus/obcpbft] Execute -> ERRO 2c3d name:"vp0"  error queueing request (queue full) for sequence number 98
```

The peers don't crash, but they do seem to stop processing transactions at this point. I am also getting an error from the REST API /chain/blocks/<n> which returns an empty block - that is I get a normal HTTP response but the block contains no transactions.

**Comment by jyellick** [comment] 2016-04-13 17:37
@bcbrock Could you post DEBUG level logs? The `queue full` message should really be reduced to a warning, rather than an error.  It is only an error in certain conditions, but more often indicates that state transfer is being too slow to catch up with the current rate of transactions.  This should not break the network, though if you attempt to query the node which is catching up, you may find missing blocks.

**Comment by bcbrock** [comment] 2016-04-13 17:43
@jyellick Would you agree that if the chain were missing a block, the REST API should return an error (block not found) rather than an empty block?

**Comment by jyellick** [comment] 2016-04-13 17:49
@bcbrock Yes, absolutely.  I agree that this is a bug.  My suspicion is that the peer is currently performing state transfer and so his block height does not necessarily match the number of blocks he has.  This is probably fooling the error checking that exists at that layer which assumes the chain is always unbroken.

I think we need to think about a policy for more clearly handling requests when a replica knows its state is not complete.  Do we make a best effort to return a correct result? Do we reject all queries? This seems like it should be a well studied problem, maybe @chetmurthy could weigh in?

**Comment by bcbrock** [comment] 2016-04-13 18:05
@jyellick Here are all of the logs. Looks like vp1 may have had a problem, vp1_logs/stderr is much shorter than the logs of all of the other peers.

[obclogs.tar.gz](https://github.com/hyperledger/fabric/files/217694/obclogs.tar.gz)

**Comment by jyellick** [comment] 2016-04-13 19:43
@bcbrock Thanks for posting the logs, they showed a definite bug in the pbft executor split that is fixed in the above PR.  Once it is merged, please retest.

**Comment by jyellick** [comment] 2016-04-14 23:36
@bcbrock I've managed to put together a temporary workaround which solves the high throughput problems for me. https://github.com/jyellick/fabric/tree/temporary-workaround

This is not intended to be a permanent solution, but wanted to try to unblock your tests.

I'm not entirely sure I understand the nuances of SOAPUI, as I seem to see more requests on the validator side than I intended to send, but my local test was able to send 1000 requests on 19 threads, leaving the network in a responsive state after about 2 minutes of processing.  This is only around 8 requests per second, but this is also with security on, running all replicas on my laptop inside vagrant.

(Note, I set CORE_PBFT_GENERAL_LOGMULTIPLIER=4 for this test, you may also see slightly better performance increasing CORE_PBFT_GENERAL_K from 10 to some higher value, but I do not think consensus is the performance bottleneck in this case)

**Comment by jyellick** [comment] 2016-04-15 20:56
@bcbrock @dongmingh I know I have cried wolf a few times about this being 'fixed', but this has turned out to be the combination of a number of different bugs.  The latest PR seems to fix the remaining problems.  I am no longer able to cause the network to lock up even when rapidly pushing 1000 requests.

Please retest, and if you observe other issues (which are not related to the network deadlocking) please open new issues.

I believe this issue is fixed, pending confirmation.

**Comment by bcbrock** [comment] 2016-04-16 00:21
@jyellick Hi Jason, I have good news and bad news. The good news is that my stress test, sending 10,000 back-to-back TX to peer 0 in a 4-peer batch consensus network runs to completion. The bad news is that it seems certain it is creating empty blocks _on peer 0_, see #1091. The other peers are OK and their blockchains match. This observation is repeatable, although it happens at different blocks each test. Note these queries were made LONG after block 71 was committed.

```
vagrant@hyperledger-devenv:v0.0.9-0c353b1:/opt/gopath/src/github.ibm.com/bcbrock/busywork/scripts$ curl http://172.17.0.2:5000/chain/blocks/71
null
vagrant@hyperledger-devenv:v0.0.9-0c353b1:/opt/gopath/src/github.ibm.com/bcbrock/busywork/scripts$ curl http://172.17.0.3:5000/chain/blocks/71
{"transactions":[{"type":2,"chaincodeID":"EoABOGIzZWVlMzc4YzNkMWFlM2VkMzhmZjJiODQwZGUxMDRkODM2YmViNzAzYjhlNGY5YTU2NDI1Yjg5NzNmODc4NmE1ZTEzNTU1MDcxMDQ0YTY3N2IwN2QyYjYyYWYxOWRiMGMwZTc4Mzg5ZmZjNGM4MDE0MDAwMzZkOTdlZTlhMDA=","payload":"CpkBCAESgwESgAE4YjNlZWUzNzhjM2QxYWUzZWQzOGZmMmI4NDBkZTEwNGQ4MzZiZWI3MDNiOGU0ZjlhNTY0MjViODk3M2Y4Nzg2YTVlMTM1NTUwNzEwNDRhNjc3YjA3ZDJiNjJhZjE5ZGIwYzBlNzgzODlmZmM0YzgwMTQwMDAzNmQ5N2VlOWEwMBoPCglpbmNyZW1lbnQSAmEx","uuid":"8cd29a01-78c0-4e3b-a70a-e274ada79a4b","timestamp":{"seconds":1460763055,"nanos":694453131}}],"stateHash":"8tlRTVAX85iYcrGm1jTxIPxSHi+Y3BAw79I4rJJ7gBSp/KGx3JJ8qDrRHzl20cx4HsaJYkMj2XPFbWIO7R5PhA==","previousBlockHash":"OFftj1YuZlIVA1kA+Q3RCOVncTtn+eKI7LVvzyQSt0HQqaEJilr2VD9TYRySt4E0KhXMwxQVL/0B7DrPdc2pbw==","nonHashData":{"localLedgerCommitTimestamp":{"seconds":1460763056,"nanos":546404953}}}
vagrant@hyperledger-devenv:v0.0.9-0c353b1:/opt/gopath/src/github.ibm.com/bcbrock/busywork/scripts$ curl http://172.17.0.4:5000/chain/blocks/71
{"transactions":[{"type":2,"chaincodeID":"EoABOGIzZWVlMzc4YzNkMWFlM2VkMzhmZjJiODQwZGUxMDRkODM2YmViNzAzYjhlNGY5YTU2NDI1Yjg5NzNmODc4NmE1ZTEzNTU1MDcxMDQ0YTY3N2IwN2QyYjYyYWYxOWRiMGMwZTc4Mzg5ZmZjNGM4MDE0MDAwMzZkOTdlZTlhMDA=","payload":"CpkBCAESgwESgAE4YjNlZWUzNzhjM2QxYWUzZWQzOGZmMmI4NDBkZTEwNGQ4MzZiZWI3MDNiOGU0ZjlhNTY0MjViODk3M2Y4Nzg2YTVlMTM1NTUwNzEwNDRhNjc3YjA3ZDJiNjJhZjE5ZGIwYzBlNzgzODlmZmM0YzgwMTQwMDAzNmQ5N2VlOWEwMBoPCglpbmNyZW1lbnQSAmEx","uuid":"8cd29a01-78c0-4e3b-a70a-e274ada79a4b","timestamp":{"seconds":1460763055,"nanos":694453131}}],"stateHash":"8tlRTVAX85iYcrGm1jTxIPxSHi+Y3BAw79I4rJJ7gBSp/KGx3JJ8qDrRHzl20cx4HsaJYkMj2XPFbWIO7R5PhA==","previousBlockHash":"OFftj1YuZlIVA1kA+Q3RCOVncTtn+eKI7LVvzyQSt0HQqaEJilr2VD9TYRySt4E0KhXMwxQVL/0B7DrPdc2pbw==","nonHashData":{"localLedgerCommitTimestamp":{"seconds":1460763056,"nanos":772633954}}}
vagrant@hyperledger-devenv:v0.0.9-0c353b1:/opt/gopath/src/github.ibm.com/bcbrock/busywork/scripts$ curl http://172.17.0.5:5000/chain/blocks/71
{"transactions":[{"type":2,"chaincodeID":"EoABOGIzZWVlMzc4YzNkMWFlM2VkMzhmZjJiODQwZGUxMDRkODM2YmViNzAzYjhlNGY5YTU2NDI1Yjg5NzNmODc4NmE1ZTEzNTU1MDcxMDQ0YTY3N2IwN2QyYjYyYWYxOWRiMGMwZTc4Mzg5ZmZjNGM4MDE0MDAwMzZkOTdlZTlhMDA=","payload":"CpkBCAESgwESgAE4YjNlZWUzNzhjM2QxYWUzZWQzOGZmMmI4NDBkZTEwNGQ4MzZiZWI3MDNiOGU0ZjlhNTY0MjViODk3M2Y4Nzg2YTVlMTM1NTUwNzEwNDRhNjc3YjA3ZDJiNjJhZjE5ZGIwYzBlNzgzODlmZmM0YzgwMTQwMDAzNmQ5N2VlOWEwMBoPCglpbmNyZW1lbnQSAmEx","uuid":"8cd29a01-78c0-4e3b-a70a-e274ada79a4b","timestamp":{"seconds":1460763055,"nanos":694453131}}],"stateHash":"8tlRTVAX85iYcrGm1jTxIPxSHi+Y3BAw79I4rJJ7gBSp/KGx3JJ8qDrRHzl20cx4HsaJYkMj2XPFbWIO7R5PhA==","previousBlockHash":"OFftj1YuZlIVA1kA+Q3RCOVncTtn+eKI7LVvzyQSt0HQqaEJilr2VD9TYRySt4E0KhXMwxQVL/0B7DrPdc2pbw==","nonHashData":{"localLedgerCommitTimestamp":{"seconds":1460763056,"nanos":701178898}}}
vagrant@hyperledger-devenv:v0.0.9-0c353b1:/opt/gopath/src/github.ibm.com/bcbrock/busywork/scripts$ 
```

Empty blocks come in runs. Here is a "block map" of peer 0's blockchain:

```
fabricLogger ERROR Block 71 does not parse
fabricLogger ERROR Block 72 does not parse
fabricLogger ERROR Block 73 does not parse
fabricLogger ERROR Block 74 does not parse
fabricLogger ERROR Block 75 does not parse
fabricLogger ERROR Block 76 does not parse
fabricLogger ERROR Block 77 does not parse
fabricLogger ERROR Block 78 does not parse
fabricLogger ERROR Block 79 does not parse
fabricLogger ERROR Block 80 does not parse
fabricLogger ERROR Block 81 does not parse
fabricLogger ERROR Block 82 does not parse
fabricLogger ERROR Block 83 does not parse
fabricLogger ERROR Block 84 does not parse
fabricLogger ERROR Block 85 does not parse
fabricLogger ERROR Block 86 does not parse
fabricLogger ERROR Block 87 does not parse
fabricLogger ERROR Block 88 does not parse
fabricLogger ERROR Block 89 does not parse
fabricLogger ERROR Block 90 does not parse
fabricLogger ERROR Block 91 does not parse
fabricLogger ERROR Block 92 does not parse
fabricLogger ERROR Block 93 does not parse
fabricLogger ERROR Block 94 does not parse
fabricLogger ERROR Block 95 does not parse
fabricLogger ERROR Block 131 does not parse
fabricLogger ERROR Block 132 does not parse
fabricLogger ERROR Block 133 does not parse
fabricLogger ERROR Block 134 does not parse
fabricLogger ERROR Block 135 does not parse
fabricLogger ERROR Block 136 does not parse
fabricLogger ERROR Block 137 does not parse
fabricLogger ERROR Block 138 does not parse
fabricLogger ERROR Block 139 does not parse
fabricLogger ERROR Block 140 does not parse
fabricLogger ERROR Block 141 does not parse
fabricLogger ERROR Block 142 does not parse
fabricLogger ERROR Block 143 does not parse
fabricLogger ERROR Block 144 does not parse
fabricLogger ERROR Block 145 does not parse
fabricLogger ERROR Block 146 does not parse
fabricLogger ERROR Block 147 does not parse
fabricLogger ERROR Block 148 does not parse
fabricLogger ERROR Block 149 does not parse
fabricLogger ERROR Block 150 does not parse
fabricLogger ERROR Block 151 does not parse
fabricLogger ERROR Block 152 does not parse
fabricLogger ERROR Block 153 does not parse
fabricLogger ERROR Block 154 does not parse
fabricLogger ERROR Block 155 does not parse
fabricLogger ERROR Block 156 does not parse
fabricLogger ERROR Block 157 does not parse
fabricLogger ERROR Block 158 does not parse
fabricLogger ERROR Block 159 does not parse
fabricLogger ERROR Block 160 does not parse
fabricLogger ERROR Block 161 does not parse
fabricLogger ERROR Block 162 does not parse
fabricLogger ERROR Block 163 does not parse
fabricLogger ERROR Block 164 does not parse
fabricLogger ERROR Block 165 does not parse
fabricLogger ERROR Block 166 does not parse
fabricLogger ERROR Block 167 does not parse
fabricLogger ERROR Block 168 does not parse
fabricLogger ERROR Block 169 does not parse
fabricLogger ERROR Block 170 does not parse
fabricLogger ERROR Block 171 does not parse
fabricLogger ERROR Block 172 does not parse
fabricLogger ERROR Block 173 does not parse
fabricLogger ERROR Block 174 does not parse
fabricLogger ERROR Block 175 does not parse
fabricLogger ERROR Block 176 does not parse
fabricLogger ERROR Block 177 does not parse
fabricLogger ERROR Block 178 does not parse
fabricLogger ERROR Block 179 does not parse
fabricLogger ERROR Block 180 does not parse
fabricLogger ERROR Block 181 does not parse
fabricLogger ERROR Block 182 does not parse
fabricLogger ERROR Block 183 does not parse
fabricLogger ERROR Block 184 does not parse
fabricLogger ERROR Block 185 does not parse
fabricLogger ERROR Block 186 does not parse
fabricLogger ERROR Block 187 does not parse
fabricLogger ERROR Block 188 does not parse
fabricLogger ERROR Block 189 does not parse
fabricLogger ERROR Block 190 does not parse
fabricLogger ERROR Block 191 does not parse
fabricLogger ERROR Block 192 does not parse
fabricLogger ERROR Block 193 does not parse
fabricLogger ERROR Block 194 does not parse
fabricLogger ERROR Block 195 does not parse
fabricLogger ERROR Block 196 does not parse
fabricLogger ERROR Block 197 does not parse
fabricLogger ERROR Block 198 does not parse
fabricLogger ERROR Block 199 does not parse
fabricLogger ERROR Block 200 does not parse
fabricLogger ERROR Block 201 does not parse
fabricLogger ERROR Block 202 does not parse
fabricLogger ERROR Block 203 does not parse
fabricLogger ERROR Block 204 does not parse
fabricLogger ERROR Block 205 does not parse
fabricLogger ERROR Block 211 does not parse
fabricLogger ERROR Block 212 does not parse
fabricLogger ERROR Block 213 does not parse
fabricLogger ERROR Block 214 does not parse
fabricLogger ERROR Block 215 does not parse
fabricLogger ERROR Block 216 does not parse
fabricLogger ERROR Block 217 does not parse
fabricLogger ERROR Block 251 does not parse
fabricLogger ERROR Block 252 does not parse
fabricLogger ERROR Block 253 does not parse
fabricLogger ERROR Block 254 does not parse
fabricLogger ERROR Block 255 does not parse
fabricLogger ERROR Block 256 does not parse
fabricLogger ERROR Block 257 does not parse
fabricLogger ERROR Block 258 does not parse
fabricLogger ERROR Block 259 does not parse
fabricLogger ERROR Block 260 does not parse
fabricLogger ERROR Block 261 does not parse
fabricLogger ERROR Block 262 does not parse
fabricLogger ERROR Block 263 does not parse
fabricLogger ERROR Block 264 does not parse
fabricLogger ERROR Block 265 does not parse
fabricLogger ERROR Block 266 does not parse
fabricLogger ERROR Block 267 does not parse
fabricLogger ERROR Block 268 does not parse
fabricLogger ERROR Block 269 does not parse
fabricLogger ERROR Block 270 does not parse
fabricLogger ERROR Block 271 does not parse
fabricLogger ERROR Block 272 does not parse
fabricLogger ERROR Block 273 does not parse
fabricLogger ERROR Block 274 does not parse
fabricLogger ERROR Block 275 does not parse
fabricLogger ERROR Block 276 does not parse
fabricLogger ERROR Block 277 does not parse
fabricLogger ERROR Block 278 does not parse
fabricLogger ERROR Block 279 does not parse
fabricLogger ERROR Block 280 does not parse
fabricLogger ERROR Block 281 does not parse
fabricLogger ERROR Block 282 does not parse
fabricLogger ERROR Block 283 does not parse
fabricLogger ERROR Block 284 does not parse
fabricLogger ERROR Block 285 does not parse
fabricLogger ERROR Block 286 does not parse
fabricLogger ERROR Block 287 does not parse
fabricLogger ERROR Block 288 does not parse
fabricLogger ERROR Block 289 does not parse
fabricLogger ERROR Block 290 does not parse
fabricLogger ERROR Block 291 does not parse
fabricLogger ERROR Block 292 does not parse
fabricLogger ERROR Block 293 does not parse
fabricLogger ERROR Block 294 does not parse
fabricLogger ERROR Block 295 does not parse
fabricLogger ERROR Block 296 does not parse
fabricLogger ERROR Block 297 does not parse
fabricLogger ERROR Block 298 does not parse
fabricLogger ERROR Block 299 does not parse
fabricLogger ERROR Block 591 does not parse
fabricLogger ERROR Block 592 does not parse
fabricLogger ERROR Block 593 does not parse
fabricLogger ERROR Block 594 does not parse
fabricLogger ERROR Block 595 does not parse
fabricLogger ERROR Block 596 does not parse
fabricLogger ERROR Block 597 does not parse
fabricLogger ERROR Block 598 does not parse
fabricLogger ERROR Block 599 does not parse
fabricLogger ERROR Block 600 does not parse
fabricLogger ERROR Block 601 does not parse
fabricLogger ERROR Block 602 does not parse
fabricLogger ERROR Block 603 does not parse
fabricLogger ERROR Block 604 does not parse
fabricLogger ERROR Block 605 does not parse
fabricLogger ERROR Block 606 does not parse
fabricLogger ERROR Block 607 does not parse
fabricLogger ERROR Block 631 does not parse
fabricLogger ERROR Block 632 does not parse
fabricLogger ERROR Block 633 does not parse
fabricLogger ERROR Block 634 does not parse
fabricLogger ERROR Block 635 does not parse
fabricLogger ERROR Block 636 does not parse
fabricLogger ERROR Block 637 does not parse
fabricLogger ERROR Block 638 does not parse
fabricLogger ERROR Block 639 does not parse
fabricLogger ERROR Block 640 does not parse
fabricLogger ERROR Block 641 does not parse
fabricLogger ERROR Block 642 does not parse
fabricLogger ERROR Block 643 does not parse
fabricLogger ERROR Block 644 does not parse
fabricLogger ERROR Block 645 does not parse
fabricLogger ERROR Block 646 does not parse
fabricLogger ERROR Block 647 does not parse
fabricLogger ERROR Block 648 does not parse
fabricLogger ERROR Block 649 does not parse
fabricLogger ERROR Block 650 does not parse
fabricLogger ERROR Block 651 does not parse
fabricLogger ERROR Block 652 does not parse
fabricLogger ERROR Block 653 does not parse
fabricLogger ERROR Block 654 does not parse
fabricLogger ERROR Block 655 does not parse
fabricLogger ERROR Block 656 does not parse
fabricLogger ERROR Block 657 does not parse
fabricLogger ERROR Block 658 does not parse
fabricLogger ERROR Block 659 does not parse
fabricLogger ERROR Block 660 does not parse
fabricLogger ERROR Block 661 does not parse
fabricLogger ERROR Block 662 does not parse
fabricLogger ERROR Block 663 does not parse
fabricLogger ERROR Block 664 does not parse
fabricLogger ERROR Block 665 does not parse
fabricLogger ERROR Block 666 does not parse
fabricLogger ERROR Block 667 does not parse
fabricLogger ERROR Block 668 does not parse
fabricLogger ERROR Block 669 does not parse
fabricLogger ERROR Block 670 does not parse
fabricLogger ERROR Block 671 does not parse
fabricLogger ERROR Block 672 does not parse
fabricLogger ERROR Block 673 does not parse
fabricLogger ERROR Block 1031 does not parse
fabricLogger ERROR Block 1032 does not parse
fabricLogger ERROR Block 1033 does not parse
fabricLogger ERROR Block 1034 does not parse
fabricLogger ERROR Block 1035 does not parse
fabricLogger ERROR Block 1036 does not parse
fabricLogger ERROR Block 1037 does not parse
fabricLogger ERROR Block 1038 does not parse
fabricLogger ERROR Block 1039 does not parse
fabricLogger ERROR Block 1040 does not parse
fabricLogger ERROR Block 1041 does not parse
fabricLogger ERROR Block 1042 does not parse
fabricLogger ERROR Block 1043 does not parse
fabricLogger ERROR Block 1071 does not parse
fabricLogger ERROR Block 1072 does not parse
fabricLogger ERROR Block 1073 does not parse
fabricLogger ERROR Block 1074 does not parse
fabricLogger ERROR Block 1075 does not parse
fabricLogger ERROR Block 1076 does not parse
fabricLogger ERROR Block 1077 does not parse
fabricLogger ERROR Block 1078 does not parse
fabricLogger ERROR Block 1079 does not parse
fabricLogger ERROR Block 1080 does not parse
fabricLogger ERROR Block 1081 does not parse
fabricLogger ERROR Block 1082 does not parse
fabricLogger ERROR Block 1083 does not parse
fabricLogger ERROR Block 1084 does not parse
fabricLogger ERROR Block 1085 does not parse
fabricLogger ERROR Block 1086 does not parse
fabricLogger ERROR Block 1087 does not parse
fabricLogger ERROR Block 1088 does not parse
fabricLogger ERROR Block 1089 does not parse
fabricLogger ERROR Block 1090 does not parse
fabricLogger ERROR Block 1091 does not parse
fabricLogger ERROR Block 1092 does not parse
fabricLogger ERROR Block 1093 does not parse
fabricLogger ERROR Block 1094 does not parse
fabricLogger ERROR Block 1095 does not parse
fabricLogger ERROR Block 1096 does not parse
fabricLogger ERROR Block 1097 does not parse
fabricLogger ERROR Block 1098 does not parse
fabricLogger ERROR Block 1099 does not parse
fabricLogger ERROR Block 1100 does not parse
fabricLogger ERROR Block 1101 does not parse
fabricLogger ERROR Block 1102 does not parse
fabricLogger ERROR Block 1103 does not parse
fabricLogger ERROR Block 1104 does not parse
fabricLogger ERROR Block 1105 does not parse
fabricLogger ERROR Block 1106 does not parse
fabricLogger ERROR Block 1107 does not parse
```

**Comment by jyellick** [comment] 2016-04-16 01:12
@bcbrock Thanks for the confirmation.  It sounds like you're in agreement, that this particular bug is squashed? If so, can you close this, and I'll focus on #1091 ?

**Comment by bcbrock** [comment] 2016-04-16 15:27
@dongmingh - Do you you agree this can be closed? (I can't close it since you created it.)

**Comment by srderson** [comment] 2016-04-16 16:46
Will close and let @dongmingh reopen if needed.

**Closed as completed by srderson** 2016-04-16 16:46 UTC
Labels: bug, consensus, sev2, statetransfer
